### PR TITLE
Modify User Interface for Index File

### PR DESCRIPTION
**Pull request by mmuhamadamirzaidi**

### CODE REVIEW

**Comment by anku580** [comment]
@mmuhamadamirzaidi Can you please provide a screenshot?

**Comment by mmuhamadamirzaidi** [comment]
Sure! A second.

**Comment by mmuhamadamirzaidi** [comment]
image

**Comment by anku580** [comment]
@mmuhamadamirzaidi This looks amazing, can you please resolve merge conflicts?

**Comment by mmuhamadamirzaidi** [comment]
Sure. Give me a few moments

**Comment by mmuhamadamirzaidi** [comment]
Done @anku580

**Comment by anku580** [comment]
@mmuhamadamirzaidi Just having few thoughts, maybe we can work this out togerther-

With the current implementation, don't you think it would be difficult for naive user to add their names. 
A lot of people will keep on adding their names and it would get very difficult with such implementation to maintain.

Can we keep it as simple as possible.

Otherwise, you've done a great work man :+1:

**Comment by mmuhamadamirzaidi** [comment]
Then what is the best solution @anku580 ?

**Comment by anku580** [comment]
@mmuhamadamirzaidi There are two solutions that I can think of - 
1. You can try creating a reusable function that can serve it as a component and each person can add data to it.
2. Instead of adding cards, you can try to create tables or sort of lists to represent github or linkdin sections.

**Pull request closed without merging**
