### PR TITLE
btn color changed

### PR DESCRIPTION
**Pull request by akriity**
Screenshot (898)
I changed the search and dark mode button color to theme color of hacktober2020 as green color was not looking good and added my links.As you can now see, on hover the search btn color looks like that as well as the slider color aster enabling dark mode

### CODE REVIEW

**Comment by anku580** [comment]
@Aacrity can you please add a screenshot as it would make easy for me to see the changes you have made in UI.

**Comment by akriity** [comment]
> @Aacrity can you please add a screenshot as it would make easy for me to see the changes you have made in UI.



> @Aacrity can you please add a screenshot as it would make easy for me to see the changes you have made in UI.

please do check my edited comment above

**Comment by anku580** [comment]
@Aacrity looks amazing, approving the PR.

**Comment by akriity** [comment]
Thank you so much..this was my first ever PR.

**Comment by anku580** [comment]
@Aacrity seriously, it does not look like that way. You did ana amazing job, keep rocking.

Let’s connect on linkedin.

**Pull request merged**
