### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by anushkarthik05**
Added 'Anush Karthik S' Github and LinkedIn profile details , changed background and text color details and added hover effects.

### CODE REVIEW

**Comment by anku580** [comment]
@anushkarthik05 Can you resolve the merge conflicts?

**Comment by anushkarthik05** [comment]
@anku580 How to resolve it?

**Comment by anushkarthik05** [comment]
Should I change the file name? @anku580

**Comment by anku580** [comment]
You need to first see what are the conflicts coming and then try resolve those commits either by adding a new commit or modifying the existing commit.

**Comment by anku580** [comment]
Hey no, you are not allowed to add a new file. Please remove the `index1.html` file.

**Comment by anushkarthik05** [comment]
> Hey no, you are not allowed to add a new file. Please remove the `index1.html` file.

Sorry :-(

**Comment by anushkarthik05** [comment]
@anku580 Thank you for helping me out.
I have resolved the conflict and removed index1.html as well

**Comment by anku580** [comment]
Hi @anushkarthik05 can you please pull the latest code and just add your github username and linkedin username because the UI has been modified by someone else.

**Comment by anushkarthik05** [comment]
> Hi @anushkarthik05 can you please pull the latest code and just add your github username and linkedin username because the UI has been modified by someone else.

Ok

**Pull request closed without merging**
