### PR TITLE
Updated index file

### PR DESCRIPTION
**Pull request by tanujajoshi1**
I hope the pr gets accepted
Issue #9

### CODE REVIEW

**Comment by anku580** [comment]
Hi @tanujajoshi1 can you please share the screenshot of how the UI looks now?

**Comment by tanujajoshi1** [comment]
Screenshot from 2020-10-02 09-59-15
Here's the screenshot. I've made a little changes. Hope they are fine.

**Comment by anku580** [comment]
@tanujajoshi1 actually the UI has been completely changed, can you please pull the latest code and work on it?

**Comment by tanujajoshi1** [comment]
Okay  I can try

**Comment by anku580** [comment]
@tanujajoshi1 There are some merge conflicts coming. If you want to learn how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8) created by me.

**Pull request closed without merging**
