### PR TITLE
[Add]:navbar renovated

### PR DESCRIPTION
**Pull request by infern018**
navb

I modified the navbar according to hacktober font scheme, but some merge conflicts are coming up,

@anku580  please review

### CODE REVIEW

**Comment by infern018** [comment]
resolved the conflict :P

**Comment by anku580** [comment]
@infern018 Good one, it would be great if you can also add the icon along with `HacktoberFest` text

**Comment by infern018** [comment]
navb2
@anku580  pls review...

**Comment by anku580** [comment]
Awesome :) 

Thank you for contributing 👍

**Review by anku580 — APPROVED** [review]

**Pull request merged**
