### PR TITLE
Updated index.html

### PR DESCRIPTION
**Pull request by HarshitChauhan**

### CODE REVIEW

**Comment by anku580** [comment]
@HarshitChauhan Can you please resolve the merge conflicts?

**Comment by HarshitChauhan** [comment]
> @HarshitChauhan Can you please resolve the merge conflicts?

i dont know how to resolve this conflict please help

**Comment by anku580** [comment]
@HarshitChauhan, to resolve the merge conflicts, you need to first see what are the conflicts coming and then add a new commit so that these conflict won't come in your new commit. 

To simplyfy, you can pull the latest code again using `git pull origin master` and then update your PR.

**Comment by anku580** [comment]
@HarshitChauhan There are some merge conflicts coming. If you want to learn how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8) created by me.

**Pull request closed without merging**
