### PR TITLE
Added dark mode feature for The Website

### PR DESCRIPTION
**Pull request by saiharsha-22**
I have added a new feature for Website, you can switch the website to the dark theme or normal theme. The dark theme will be working when the button is clicked. And you can get back to the normal theme.

when normal theme
Screenshot (404)

dark theme 
Screenshot (403)

### CODE REVIEW

**Comment by anku580** [comment]
@saiharsha-22 This looks interesting, can you change the button styling and make it look more attractive?

**Comment by saiharsha-22** [comment]
@anku580 Ok I will try and update the file. you liked it?

**Comment by anku580** [comment]
@saiharsha-22 Yes, I very much liked it. 

There are some merge conflicts coming. If you want to learn how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8) created by me.

**Comment by saiharsha-22** [comment]
@anku580 I have updated and removed the merge conflicts you can safely merge it now

**Comment by saiharsha-22** [comment]
@anku580 I have updated the button style can you please check it once
Screenshot (405)

**Comment by saiharsha-22** [comment]
@anku580 I have made changes in the pull request you can merge now.

before switching dark mode
Screenshot (405)
After Switching the dark mode.
Screenshot (406)

**Review by anku580 — APPROVED** [review]

**Comment by anku580** [comment]
Merged.... thank you for contributing

**Pull request merged**
